version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: symfony-app
        working_dir: /var/www
        volumes:
            - .:/var/www:cached
        environment:
            PHP_IDE_CONFIG: "serverName=symfony"
        networks:
            - symfony-network
        ports:
            - "9000:9000" # PHP-FPM

    nginx:
        image: nginx:alpine
        container_name: symfony-nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - symfony-network

    db:
        image: mariadb:10.9
        container_name: symfony-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - "3306:3306"
        networks:
            - symfony-network
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:

networks:
    symfony-network:
        driver: bridge
